const PDFDocument = require("pdfkit");
const fs = require("fs").promises;
const path = require("path");

/**
 * 영수증 JSON 데이터를 기반으로 PDF 영수증 생성
 * @param {Object} receiptData - 영수증 JSON 데이터
 * @returns {Object} 생성 결과
 */
const generatePDFReceipt = async (receiptData) => {
  try {
    console.log("PDF 생성 시작:", receiptData.receiptId);

    const doc = new PDFDocument({
      size: "A4",
      margin: 50,
    });

    // PDF 파일 경로 설정
    const receiptsDir = path.join(__dirname, "../../receipts");
    const pdfFileName = `${receiptData.receiptId}.pdf`;
    const pdfFilePath = path.join(receiptsDir, pdfFileName);

    console.log("PDF 파일 경로:", pdfFilePath);

    // PDF 파일 스트림 생성
    const writeStream = require("fs").createWriteStream(pdfFilePath);
    doc.pipe(writeStream);

    console.log("PDF 내용 작성 시작...");

    // PDF 내용 작성 (await 제거)
    createReceiptContent(doc, receiptData);

    console.log("PDF 내용 작성 완료, PDF 종료 중...");

    // PDF 완료
    doc.end();

    return new Promise((resolve, reject) => {
      writeStream.on("finish", () => {
        console.log("PDF 파일 쓰기 완료:", pdfFileName);
        resolve({
          success: true,
          pdfPath: pdfFilePath,
          pdfFileName: pdfFileName,
        });
      });
      writeStream.on("error", (error) => {
        console.error("PDF 파일 쓰기 오류:", error);
        reject({
          success: false,
          error: error.message,
        });
      });
    });
  } catch (error) {
    console.error("PDF 생성 중 오류:", error);
    return {
      success: false,
      error: error.message,
    };
  }
};

/**
 * PDF 영수증 내용 생성
 * @param {PDFDocument} doc - PDF 문서 객체
 * @param {Object} receiptData - 영수증 데이터
 */
const createReceiptContent = (doc, receiptData) => {
  doc.fontSize(18).text("PURCHASE RECEIPT", { align: "center" });
  doc.moveDown();

  doc.fontSize(10).text(`Receipt ID: ${receiptData.receiptId}`);
  doc.text(`Date: ${new Date(receiptData.timestamp).toLocaleString("en-US")}`);
  doc.moveDown();

  doc.text(`Project ID: ${receiptData.purchase.projectId}`);
  doc.text(`Request ID: ${receiptData.purchase.requestId}`);
  doc.text(`Buyer: ${receiptData.purchase.buyer}`);
  doc.text(`Token ID: ${receiptData.purchase.tokenId}`);
  doc.text(`Amount: ${receiptData.purchase.amountInDP} DP`);
  doc.moveDown();

  doc.text(`Project Name: ${receiptData.nft.projectName}`);
  doc.text(`Description: ${receiptData.nft.description}`);
  doc.moveDown();

  doc.text("Distribution:");
  receiptData.distribution.forEach((dist) => {
    doc.text(`Role: ${dist.role}`);
    doc.text(`Recipient: ${dist.recipient}`);
    doc.text(`Net Amount: ${parseFloat(dist.netAmount) / 1e18} DP`);
    doc.text(`Platform Fee: ${parseFloat(dist.fee) / 1e18} DP`);
    doc.text(`Status: ${dist.isMatched ? "Verified" : "Error"}`);
    doc.moveDown();
  });

  doc.text(`Transaction Hash: ${receiptData.transaction.hash}`);
  doc.text(`Block Number: ${receiptData.transaction.blockNumber}`);
  doc.text(`Gas Used: ${receiptData.transaction.gasUsed}`);
  doc.moveDown();

  doc.text(
    `Total Amount: ${parseFloat(receiptData.summary.totalAmount) / 1e18} DP`
  );
  doc.text(
    `Total Platform Fees: ${
      parseFloat(receiptData.summary.totalFees) / 1e18
    } DP`
  );
  doc.text(
    `Total Net Distribution: ${
      parseFloat(receiptData.summary.totalNetDistribution) / 1e18
    } DP`
  );
  doc.text(`Participants: ${receiptData.summary.participants}`);

  doc.moveDown();
  doc
    .fontSize(8)
    .text(
      "This receipt is automatically generated by the DressDio NFT Marketplace."
    );
};

// 역할별 색상
const getRoleColor = (role) => {
  const colors = {
    brand: "#e74c3c",
    artist: "#3498db",
    influencer: "#f39c12",
  };
  return colors[role] || "#95a5a6";
};

/**
 * 영수증 ID로 PDF 파일 경로 조회
 * @param {string} receiptId - 영수증 ID
 * @returns {string} PDF 파일 경로
 */
const getPDFPath = (receiptId) => {
  const receiptsDir = path.join(__dirname, "../../receipts");
  return path.join(receiptsDir, `${receiptId}.pdf`);
};

/**
 * PDF 파일 존재 여부 확인
 * @param {string} receiptId - 영수증 ID
 * @returns {boolean} 파일 존재 여부
 */
const checkPDFExists = async (receiptId) => {
  try {
    const pdfPath = getPDFPath(receiptId);
    await fs.access(pdfPath);
    return true;
  } catch {
    return false;
  }
};

/**
 * 영수증 JSON 데이터를 기반으로 PDF 생성 (없는 경우에만)
 * @param {Object} receiptData - 영수증 JSON 데이터
 * @returns {Object} 생성 결과
 */
const generatePDFIfNotExists = async (receiptData) => {
  try {
    // PDF가 이미 존재하는지 확인
    const exists = await checkPDFExists(receiptData.receiptId);

    if (exists) {
      return {
        success: true,
        pdfPath: getPDFPath(receiptData.receiptId),
        pdfFileName: `${receiptData.receiptId}.pdf`,
        message: "PDF already exists",
      };
    }

    // PDF 생성
    return await generatePDFReceipt(receiptData);
  } catch (error) {
    return {
      success: false,
      error: error.message,
    };
  }
};

module.exports = {
  generatePDFReceipt,
  generatePDFIfNotExists,
  getPDFPath,
  checkPDFExists,
};
